export enum TokenType {
  KEYWORD = "KEYWORD",
  IDENTIFIER = "IDENTIFIER",
  NUMBER = "NUMBER",
  STRING = "STRING",
  BOOLEAN = "BOOLEAN",
  ARITHMETIC_OPERATOR = "ARITHMETIC_OPERATOR",
  ASSIGNMENT_OPERATOR = "ASSIGNMENT_OPERATOR",
  COMPOUND_ASSIGNMENT = "COMPOUND_ASSIGNMENT",
  RELATIONAL_OPERATOR = "RELATIONAL_OPERATOR",
  LOGICAL_OPERATOR = "LOGICAL_OPERATOR",
  UNARY_OPERATOR = "UNARY_OPERATOR",
  LBRACKET = "LBRACKET",
  RBRACKET = "RBRACKET",
  LPAREN = "LPAREN",
  RPAREN = "RPAREN",
  COMMA = "COMMA",
  DOT = "DOT",
  NEWLINE = "NEWLINE",
  EOF = "EOF",
}

export type TokenValue = string | number | boolean | null;

export interface Token {
  type: TokenType;
  value: TokenValue;
  line: number;
  column: number;
}
